# -*- coding: utf-8 -*-
"""Witchery.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZIrN00DK2LBMK1aW-MEu5fo59ZCt42nD
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Cargar los datos
data = pd.read_csv('Datos Demográficos - Sheet1.csv')

# Limpiar nombres de columnas
data.columns = data.columns.str.strip()

# 1. Estadísticas básicas
print("Estadísticas descriptivas básicas:\n", data.describe())

# 2. Análisis por grupo (Sexo)
numeric_cols = data.select_dtypes(include='number')
grouped_by_sex = data.groupby('Sexo')[numeric_cols.columns].mean()
print("\nPromedios por sexo:\n", grouped_by_sex)

# 3. Correlación entre respuestas
correlation_matrix = data.corr(numeric_only=True)
print("\nMatriz de correlación:\n", correlation_matrix)

# Visualización de correlaciones
plt.figure(figsize=(10, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)
plt.title('Mapa de Calor de Correlaciones')
plt.show()

# 4. Histogramas de edades y puntuaciones
plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)
sns.histplot(data['Edad'], bins=8, kde=True, color='skyblue')
plt.title('Distribución de Edades')

plt.subplot(1, 2, 2)
sns.histplot(data['Sentí que mi equipo quería ganar a toda costa'], bins=5, kde=True, color='orange')
plt.title('Distribución: Ganas de ganar')

plt.tight_layout()
plt.show()

# 5. Comparación entre hombres y mujeres
plt.figure(figsize=(10, 6))
sns.barplot(x='Sexo', y='Sentí que mi equipo quería ganar a toda costa', data=data, palette='pastel')
plt.title('Comparación por Sexo: Ganas de Ganar')
plt.show()

"""1. Estadísticas Básicas

Edad media: 22.5 años, con una gran dispersión (desviación estándar de 7.9). Se observa una mezcla de participantes jóvenes y uno mucho mayor (máximo 56 años).

Trabajo en equipo y comunicación: Promedios altos cercanos a 5, lo que indica que la mayoría percibió una buena dinámica grupal.

Deseo de ganar: Media de 3.55 con desviación de 1.35. Se detecta más variabilidad, lo que indica que no todos sintieron la misma intensidad competitiva.

Relación entre equipos: Promedio bajo de 2.45, lo que sugiere que la percepción entre equipos fue más negativa o distante.

2. Análisis por Sexo

Edad promedio: Las mujeres presentan una edad promedio mayor (24 años) que los hombres (20.7 años).

Deseo de ganar: Las mujeres reportaron un mayor deseo de ganar (4.0 frente a 3.0 en los hombres).

Tensión competitiva: Mayor en mujeres (4.18 frente a 3.44 en los hombres).

Relación entre equipos: Las mujeres percibieron una relación entre equipos algo mejor (2.8 frente a 2.0 en los hombres).

Interpretación: Las mujeres percibieron una competencia más fuerte y mostraron una mayor motivación para ganar, aunque mantuvieron una percepción ligeramente mejor de la relación entre equipos.

3. Correlación entre Variables

Algunas conexiones interesantes observadas:

"Sentí que mi equipo quería ganar a toda costa" tiene una correlación positiva (+0.54) con "Hubo tensión competitiva", lo que indica que cuando hay más ganas de ganar, también aumenta la tensión entre equipos.

"Trabajo en equipo eficiente" presenta una correlación negativa (-0.48) con "Relación entre equipos", sugiriendo que centrarse solo en ganar podría afectar la conexión con el otro equipo.

"Cómo te sentiste compitiendo contra el otro equipo" tiene una fuerte correlación negativa (-0.60) con "Eficiencia en equipo", es decir, quienes se sintieron incómodos compitiendo también percibieron peor la dinámica dentro de su propio equipo.

4. Visualizaciones

Distribución de edades: La mayoría de los participantes se concentran entre los 20 y 21 años, con una excepción de una persona mayor que rompe la tendencia.

Distribución de ganas de ganar: Se observa una mezcla de participantes muy motivados (5) y otros con poca motivación (1).

Comparación por sexo: Visualmente destaca más el deseo de ganar y la tensión competitiva en las mujeres.

5. Conclusiones Generales

Equipos efectivos, pero emocionalmente divididos: A pesar de las buenas calificaciones en trabajo y comunicación, las bajas puntuaciones en la relación entre equipos sugieren una competencia más hostil.

Mujeres más motivadas, pero con más tensión: Las mujeres mostraron un mayor deseo de ganar, pero también percibieron más tensión competitiva.

La tensión impulsa y desgasta: La tensión está asociada con una mayor motivación para ganar, pero también parece afectar negativamente la dinámica interna del equipo y la percepción de la competencia.


"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Cargar los datos
data = pd.read_csv('Datos Pareja - Sheet1.csv')
data.columns = data.columns.str.strip()

# 1. Estadísticas básicas
print("Estadísticas básicas:\n", data.describe())

# 2. Relación entre cooperación y rendimiento
correlation_matrix = data.corr(numeric_only=True)
print("\nMatriz de correlación:\n", correlation_matrix)

# 3. Gráfico de dispersión: Cooperación vs Puntuación final
plt.figure(figsize=(8, 6))
sns.scatterplot(x='Percepción de trabajo en equipo para alcanzar metas', y='Puntuación final', data=data, hue='Parejas', s=100)
plt.title('Trabajo en equipo vs Puntuación final')
plt.xlabel('Percepción de Trabajo en Equipo')
plt.ylabel('Puntuación Final')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()

# 4. Comparación de desafíos ganados vs percepción de equipo
plt.figure(figsize=(10, 6))
sns.barplot(x='Parejas', y='Desafíos ganados', data=data, palette='viridis')
plt.title('Desafíos Ganados por Pareja')
plt.xticks(rotation=45)
plt.show()

# 5. Mapa de calor de correlaciones
plt.figure(figsize=(8, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)
plt.title('Mapa de Calor de Correlaciones')
plt.show()

"""1. Estadísticas Básicas

Desafíos ganados: En promedio, las parejas ganaron 3.6 desafíos, con una gran variabilidad (máximo 7, mínimo 0).

Percepción de trabajo en equipo: Media de 3.8 sobre 5, indicando una percepción positiva general del trabajo en equipo.

Puntuación final: Promedio cercano a 12, aunque algunas parejas terminaron con puntuaciones negativas.

Duración de la partida: Media de 45 minutos, pero algunas partidas se extendieron por más de una hora.

Conclusión rápida: Hay una gran dispersión en el rendimiento y las puntuaciones, lo que sugiere que no todas las parejas funcionaron igual de bien, a pesar de que la mayoría percibió una buena cooperación.

2. Correlación entre Cooperación y Rendimiento

Percepción de trabajo en equipo y puntuación final: Correlación positiva moderada (alrededor de 0.4). Indica que las parejas que percibieron una mejor cooperación tendieron a obtener mejores puntuaciones, aunque no es una relación perfecta.

Desafíos ganados vs. percepción de trabajo en equipo: Correlación baja (0.2). Sorprendentemente, ganar desafíos no está fuertemente ligado a la percepción de buen trabajo en equipo.

Duración de la partida y puntuación final: Correlación negativa (-0.5). Las partidas más largas tendieron a acabar con puntuaciones más bajas, posiblemente debido al agotamiento o estrategias menos efectivas.

Conclusión rápida: El sentimiento de buen trabajo en equipo influye algo en la puntuación final, pero no tanto en los desafíos ganados. Las partidas largas parecen ser más agotadoras que productivas.

3. Visualización e Interpretación Gráfica

Gráfico de dispersión (Trabajo en equipo vs Puntuación final): Se observa que las parejas con alta percepción de trabajo en equipo generalmente alcanzan puntuaciones más altas, aunque hay excepciones.

Interpretación: Algunas parejas con baja percepción aún lograron buenas puntuaciones, lo que podría indicar que la estrategia jugó un rol más fuerte que la cooperación.

Gráfico de barras (Desafíos ganados por pareja): Las parejas que ganaron más desafíos no son necesariamente las que tuvieron mejor percepción de equipo.

Interpretación: Ganar desafíos no garantiza que la experiencia del equipo sea buena. Algunas parejas "ganaron pero sufrieron".

Mapa de calor (Correlaciones): La relación más destacada es la negativa entre duración de partida y puntuación final.

Interpretación: Optimizar el tiempo podría ser una clave importante para mejorar los resultados.

4. Conclusiones Finales

La cooperación percibida ayuda, pero no garantiza la victoria: Las parejas con buena percepción de trabajo en equipo tienden a obtener mejores puntuaciones, pero algunas lograron altos puntajes sin sentir que cooperaban bien.

El tiempo es un factor clave: Las partidas más largas se asocian con peores puntuaciones. Es posible que la fatiga afecte el rendimiento o que los equipos que tardan más tomen decisiones menos eficientes.

Ganar desafíos no siempre se alinea con la percepción de buen equipo: Algunas parejas ganaron más desafíos, pero calificaron mal la cooperación. Esto sugiere que "ganar" no siempre significa trabajar en armonía.
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Cargar los datos
data = pd.read_csv('Datos Rondas - Sheet1.csv')

# Limpiar nombres de columnas
data.columns = data.columns.str.strip().str.replace(' ', '_').str.lower()

# 1. Correlación entre paridad competitiva y diferencia de puntuación
plt.figure(figsize=(8, 6))
sns.scatterplot(x='coeficiente_de_paridad_competitiva', y='diferencia_puntuación_entre_equipos', data=data)
plt.title('Paridad competitiva vs Diferencia de puntuación')
plt.xlabel('Coeficiente de Paridad Competitiva')
plt.ylabel('Diferencia de Puntuación entre Equipos')
plt.show()

# 2. Relación entre interferencia estratégica y diferencia de puntuación
plt.figure(figsize=(8, 6))
sns.boxplot(x='nivel_de_interferencia_estratégica', y='diferencia_puntuación_entre_equipos', data=data)
plt.title('Interferencia estratégica vs Diferencia de puntuación')
plt.xlabel('Nivel de Interferencia Estratégica')
plt.ylabel('Diferencia de Puntuación entre Equipos')
plt.show()

# 3. Cambio de liderazgo vs diferencia de puntuación
plt.figure(figsize=(8, 6))
sns.regplot(x='tasa_de_cambio_de_liderazgo', y='diferencia_puntuación_entre_equipos', data=data, scatter_kws={'s': 100})
plt.title('Tasa de cambio de liderazgo vs Diferencia de puntuación')
plt.xlabel('Tasa de Cambio de Liderazgo')
plt.ylabel('Diferencia de Puntuación entre Equipos')
plt.show()

# 4. Comparación entre tiempo promedio e intercambio de información
plt.figure(figsize=(8, 6))
sns.scatterplot(x='tiempo_promedio_en_resolver_tareas_en_segundos', y='cantidad_de_intercambio_de_información', data=data)
plt.title('Tiempo de resolución vs Intercambio de información')
plt.xlabel('Tiempo Promedio en Resolver Tareas (segundos)')
plt.ylabel('Cantidad de Intercambio de Información')
plt.show()

# 5. Tendencias por ronda
plt.figure(figsize=(8, 6))
sns.lineplot(x='número_ronda', y='diferencia_puntuación_entre_equipos', data=data, marker='o')
plt.title('Diferencia de puntuación a lo largo de las rondas')
plt.xlabel('Número de Ronda')
plt.ylabel('Diferencia de Puntuación entre Equipos')
plt.show()

"""1. Paridad competitiva vs Diferencia de puntuación

Observación:

Si los puntos se agrupan cerca de 0 en la diferencia de puntuación cuando la paridad competitiva es alta, eso indicaría que los equipos estaban muy equilibrados. Si hay dispersión aún con alta paridad, puede ser que la estrategia pesó más que la igualdad.

Interpretación:

Si la correlación es negativa o cercana a cero, la paridad competitiva no asegura una diferencia de puntuación baja (equipos equilibrados aún pueden tener resultados dispares).

Si es positiva, los equipos más balanceados terminan con márgenes más pequeños entre sí, lo que implica competencia cerrada.

2. Interferencia estratégica vs Diferencia de puntuación

Observación:

Si los equipos con alta interferencia terminan con diferencias grandes o más bajas, revela si sabotear ayuda o sólo causa caos mutuo.

Interpretación:

Si las rondas con más interferencia tienen diferencias de puntuación más altas → la estrategia agresiva beneficia al equipo que lidera.

Si las diferencias son más pequeñas o negativas → interferir causa más daño a ambos equipos que beneficio para uno solo.

3. Tasa de cambio de liderazgo vs Diferencia de puntuación

Observación:

Muchas alternancias pueden indicar una competencia muy ajustada. Si la diferencia final sigue siendo baja tras muchos cambios, es prueba de que ambos equipos estaban luchando constantemente.

Interpretación:

Alta tasa + baja diferencia → Equipos reñidos, pero ninguno logró dominar.

Alta tasa + alta diferencia → Un equipo tuvo "remontadas" que no pudo sostener, y el otro aprovechó.

Baja tasa + baja diferencia → Ronda estable y pareja.

Baja tasa + alta diferencia → Dominio claro desde el principio.

4. Tiempo promedio en resolver tareas vs Cantidad de intercambio de información

Observación:

Si los equipos que más se comunican resuelven más rápido, entonces la comunicación es clave para la eficiencia. Si la tendencia es inversa, podría haber exceso de discusión que retrasa.

Interpretación:

Más comunicación + menos tiempo → Comunicación efectiva.

Más comunicación + más tiempo → Se distraen o se confunden.

Poca comunicación + menos tiempo → Equipos más autónomos y directos.

5. Tendencias por ronda (Diferencia de puntuación a lo largo de las rondas)

Observación:

Si las diferencias de puntuación disminuyen con cada ronda, los equipos aprenden y se equilibran. Si aumentan, es señal de que un equipo encontró una estrategia dominante.

Interpretación:

Tendencia a la baja → Mejora general del equilibrio entre equipos.

Tendencia al alza → Un equipo perfeccionó su estrategia y amplió su ventaja.

Tendencia en zigzag → Rondas caóticas, con cambios de estrategia entre equipos.

 Conclusión general:

Si vemos que las rondas finales son más reñidas y con menos cambios de liderazgo, los equipos aprendieron a optimizar sus estrategias.

Si la interferencia causa más daño que beneficio, enfocarse en la cooperación puede ser clave.

La comunicación efectiva, sin excesos, parece crucial para tiempos más rápidos y diferencias más pequeñas.
"""